project:
  type: website
  output-dir: docs

execute: 
  eval: FALSE
  
website:
  sidebar:
    background: "dark"
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - whole_muscle_scrnaseq.qmd
      - myob_single_nuc.qmd
      - atac_seq.qmd
      - conda_envs.qmd
      - extra_tips.qmd
      - section: "Single cell"
        contents:
          - single_cell.qmd
          - pseudotime.qmd
          - pseudobulk.qmd
  title: "Matt work summary"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - single_cell.qmd
  #     - single_nuclear.qmd
  #     - pseudotime.qmd
  #     - atac_seq.qmd

format:
  html:
    highlight-style: github
    code-copy: hover
    code-line-numbers: true
    code-block-bg: true
    # code-block-border-left: "#31BAE9"
    code-block-border-left: true
    theme: solar
    css: styles.css
    toc: true
    monobackgroundcolor: "light"

editor: visual

